name: Smoke

on:
    push: 
    workflow_dispatch: 

permissions: 
    contents: read

jobs:
    smoke:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - uses: $/
              id: pre
              with:
                install: 'false'

            - shell: bash
              run: |
                echo "node-version              = [${{steps.pre.outputs.node-version}}]"
                echo "cache-hit                 = [${{steps.pre.outputs.cache-hit}}]"
                echo "dependencies-installed    = [${{steps.pre.outputs.dependencies-installed}}]"
